[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Configure Netlify Blobs
[[blobs]]
  name = "picozen-app-data"
  function = "add-app"

[[blobs]]
  name = "picozen-app-data"
  function = "apps"

[[blobs]]
  name = "picozen-app-data"
  function = "categories"

[[blobs]]
  name = "picozen-app-data"
  function = "download"

[[blobs]]
  name = "picozen-app-data"
  function = "featured"

[[blobs]]
  name = "picozen-app-data"
  function = "scrape-app"